### ISSUE TITLE
Error on npm start at ng serve

### ISSUE THREAD

**Issue by adambu** [Hongbo-Miao/microsoft-graph-angular#1]
No idea really what is going on.  Here is my npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\adambu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.0.3
3 info using node@v4.6.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle demo-simple@0.0.0~prestart: demo-simple@0.0.0
6 silly lifecycle demo-simple@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle demo-simple@0.0.0~start: demo-simple@0.0.0
8 verbose lifecycle demo-simple@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle demo-simple@0.0.0~start: PATH: C:\Users\adambu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;F:\Source\Repos\microsoft-graph-angular\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Hewlett-Packard\HP Performance Advisor;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\adambu\AppData\Local\Microsoft\WindowsApps;.bin;C:\Users\adambu\AppData\Roaming\npm;C:\Program Files\Git;C:\Users\adambu\AppData\Roaming\Boxstarter;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle demo-simple@0.0.0~start: CWD: F:\Source\Repos\microsoft-graph-angular
11 silly lifecycle demo-simple@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
12 silly lifecycle demo-simple@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle demo-simple@0.0.0~start: Failed to exec start script
14 verbose stack Error: demo-simple@0.0.0 start: `ng serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\adambu\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\adambu\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid demo-simple@0.0.0
16 verbose cwd F:\Source\Repos\microsoft-graph-angular
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\adambu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.6.1
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error demo-simple@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the demo-simple@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the demo-simple package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs demo-simple
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls demo-simple
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by adambu** [comment]
Actually, I got this working.  It was because I had an older version of node.  You might want to put a pre-reqs section and mention what are the minimum platform versions.
